---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    #url: jdbc:mysql://localhost/pong_matcher_spring_development
    username: springpong
    password: springpong
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
